
package async.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationService", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<async.client.ReserveClothesResponse>
     */
    @WebMethod(operationName = "ReserveClothes")
    @RequestWrapper(localName = "ReserveClothes", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "async.client.ReserveClothes")
    @ResponseWrapper(localName = "ReserveClothesResponse", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "async.client.ReserveClothesResponse")
    public Response<ReserveClothesResponse> reserveClothesAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ReserveClothes")
    @RequestWrapper(localName = "ReserveClothes", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "async.client.ReserveClothes")
    @ResponseWrapper(localName = "ReserveClothesResponse", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "async.client.ReserveClothesResponse")
    public Future<?> reserveClothesAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ReserveClothesResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns async.client.UserReserve
     */
    @WebMethod(operationName = "ReserveClothes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReserveClothes", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "async.client.ReserveClothes")
    @ResponseWrapper(localName = "ReserveClothesResponse", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "async.client.ReserveClothesResponse")
    @Action(input = "http://asu.dgtu.donetsk.ua/ex/students/ReservationService/ReserveClothesRequest", output = "http://asu.dgtu.donetsk.ua/ex/students/ReservationService/ReserveClothesResponse")
    public UserReserve reserveClothes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
